CREATE DATABASE IF NOT EXISTS ${MYSQL_DB};
GRANT ALL PRIVILEGES ON ${MYSQL_DB}.* TO '${MYSQLDB_USER}'@'%' IDENTIFIED BY ${MYSQL_USER_PASSWORD};
GRANT ALL PRIVILEGES ON ${MYSQL_DB}.* TO '${MYSQLDB_USER}'@localhost IDENTIFIED BY ${MYSQL_USER_PASSWORD};